/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokedex;

import javax.swing.JButton;

/**
 *
 * @author alex
 */
public class pokidex extends javax.swing.JFrame {

    /**
     * Creates new form pokidex
     */
    public pokidex() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokedex = new javax.swing.JDialog();
        botton_21 = new javax.swing.JButton();
        botton_22 = new javax.swing.JButton();
        botton_23 = new javax.swing.JButton();
        botton_24 = new javax.swing.JButton();
        botton_25 = new javax.swing.JButton();
        botton_20 = new javax.swing.JButton();
        botton_19 = new javax.swing.JButton();
        botton_18 = new javax.swing.JButton();
        botton_17 = new javax.swing.JButton();
        botton_16 = new javax.swing.JButton();
        botton_11 = new javax.swing.JButton();
        botton_12 = new javax.swing.JButton();
        botton_13 = new javax.swing.JButton();
        botton_14 = new javax.swing.JButton();
        botton_15 = new javax.swing.JButton();
        botton_10 = new javax.swing.JButton();
        botton_9 = new javax.swing.JButton();
        botton_8 = new javax.swing.JButton();
        botton_7 = new javax.swing.JButton();
        botton_6 = new javax.swing.JButton();
        botton_1 = new javax.swing.JButton();
        botton_2 = new javax.swing.JButton();
        botton_3 = new javax.swing.JButton();
        botton_4 = new javax.swing.JButton();
        botton_5 = new javax.swing.JButton();
        Agregar_usuario = new javax.swing.JDialog();
        jComboBox_sexoJugador = new javax.swing.JComboBox<>();
        jLabel_avatarJugador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_sexo = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_edad = new javax.swing.JLabel();
        jTextField_edad = new javax.swing.JTextField();
        jLabel_region = new javax.swing.JLabel();
        jComboBox_region = new javax.swing.JComboBox<>();
        jLabel_regiones = new javax.swing.JLabel();
        jButton_guardar = new javax.swing.JButton();
        jLabel_nombre1 = new javax.swing.JLabel();
        jTextField_contraseña = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Agregar_Pokemon = new javax.swing.JDialog();
        Login = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        botton_login = new javax.swing.JButton();
        botton_crearUsuario = new javax.swing.JButton();
        botton_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        botton_21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_21.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_21ActionPerformed(evt);
            }
        });

        botton_22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_22.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_22ActionPerformed(evt);
            }
        });

        botton_23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_23.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_23ActionPerformed(evt);
            }
        });

        botton_24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_24.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_24ActionPerformed(evt);
            }
        });

        botton_25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_25.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_25ActionPerformed(evt);
            }
        });

        botton_20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_20.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_20ActionPerformed(evt);
            }
        });

        botton_19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_19.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_19ActionPerformed(evt);
            }
        });

        botton_18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_18.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_18ActionPerformed(evt);
            }
        });

        botton_17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_17.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_17ActionPerformed(evt);
            }
        });

        botton_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_16.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_16ActionPerformed(evt);
            }
        });

        botton_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_11.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_11ActionPerformed(evt);
            }
        });

        botton_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_12.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_12ActionPerformed(evt);
            }
        });

        botton_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_13.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_13ActionPerformed(evt);
            }
        });

        botton_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_14.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_14ActionPerformed(evt);
            }
        });

        botton_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_15.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_15ActionPerformed(evt);
            }
        });

        botton_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_10.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_10ActionPerformed(evt);
            }
        });

        botton_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_9.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_9ActionPerformed(evt);
            }
        });

        botton_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_8.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_8ActionPerformed(evt);
            }
        });

        botton_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_7.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_7ActionPerformed(evt);
            }
        });

        botton_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_6.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_6ActionPerformed(evt);
            }
        });

        botton_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/25.gif"))); // NOI18N
        botton_1.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_1ActionPerformed(evt);
            }
        });

        botton_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_2.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_2ActionPerformed(evt);
            }
        });

        botton_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_3.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_3ActionPerformed(evt);
            }
        });

        botton_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_4.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_4ActionPerformed(evt);
            }
        });

        botton_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/animated_question_marks_bubbling1.gif"))); // NOI18N
        botton_5.setPreferredSize(new java.awt.Dimension(60, 60));
        botton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pokedexLayout = new javax.swing.GroupLayout(pokedex.getContentPane());
        pokedex.getContentPane().setLayout(pokedexLayout);
        pokedexLayout.setHorizontalGroup(
            pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokedexLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pokedexLayout.createSequentialGroup()
                        .addComponent(botton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pokedexLayout.createSequentialGroup()
                            .addComponent(botton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pokedexLayout.createSequentialGroup()
                            .addComponent(botton_11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pokedexLayout.createSequentialGroup()
                            .addComponent(botton_16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_19, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_20, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pokedexLayout.createSequentialGroup()
                            .addComponent(botton_21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_22, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_23, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_24, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botton_25, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pokedexLayout.setVerticalGroup(
            pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokedexLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botton_14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botton_19, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_20, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_17, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botton_24, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_25, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_21, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_23, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        Agregar_usuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_sexoJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        jComboBox_sexoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_sexoJugadorActionPerformed(evt);
            }
        });
        Agregar_usuario.getContentPane().add(jComboBox_sexoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 163, -1));

        jLabel_avatarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/RedHGSS.gif"))); // NOI18N
        Agregar_usuario.getContentPane().add(jLabel_avatarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Usuario");
        Agregar_usuario.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 320, 70));

        jLabel_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setText("Nombre:");
        Agregar_usuario.getContentPane().add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel_sexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_sexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sexo.setText("Sexo:");
        Agregar_usuario.getContentPane().add(jLabel_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });
        Agregar_usuario.getContentPane().add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 310, -1));

        jLabel_edad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_edad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_edad.setText("Edad:");
        Agregar_usuario.getContentPane().add(jLabel_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jTextField_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_edadActionPerformed(evt);
            }
        });
        Agregar_usuario.getContentPane().add(jTextField_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 60, -1));

        jLabel_region.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_region.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_region.setText("Region:");
        Agregar_usuario.getContentPane().add(jLabel_region, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jComboBox_region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kanto", "Johto", "Hoenn", "Sinnoh", "Unova", "Kalos", "Alola" }));
        jComboBox_region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_regionActionPerformed(evt);
            }
        });
        Agregar_usuario.getContentPane().add(jComboBox_region, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 180, -1));

        jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-HGSS_Kanto.png"))); // NOI18N
        Agregar_usuario.getContentPane().add(jLabel_regiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 300, 240));

        jButton_guardar.setText("Guardar");
        Agregar_usuario.getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 220, 30));

        jLabel_nombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre1.setText("Contraseña:");
        Agregar_usuario.getContentPane().add(jLabel_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jTextField_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_contraseñaActionPerformed(evt);
            }
        });
        Agregar_usuario.getContentPane().add(jTextField_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 310, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/KwnCoKk.gif"))); // NOI18N
        Agregar_usuario.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout Agregar_PokemonLayout = new javax.swing.GroupLayout(Agregar_Pokemon.getContentPane());
        Agregar_Pokemon.getContentPane().setLayout(Agregar_PokemonLayout);
        Agregar_PokemonLayout.setHorizontalGroup(
            Agregar_PokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Agregar_PokemonLayout.setVerticalGroup(
            Agregar_PokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Pokedex.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 830, 320));

        botton_login.setText("LOGIN");
        getContentPane().add(botton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 300, 40));

        botton_crearUsuario.setText("Crear Usuario");
        botton_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_crearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botton_crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 300, 40));

        botton_Salir.setText("Salir");
        botton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(botton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 300, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/pokemon_sprite_gif___petalburg_woods_by_loupii-d7i3cm4.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botton_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_24ActionPerformed

    private void botton_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_25ActionPerformed

    private void botton_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_21ActionPerformed

    private void botton_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_23ActionPerformed

    private void botton_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_22ActionPerformed

    private void botton_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_16ActionPerformed

    private void botton_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_17ActionPerformed

    private void botton_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_18ActionPerformed

    private void botton_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_19ActionPerformed

    private void botton_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_20ActionPerformed

    private void botton_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_11ActionPerformed

    private void botton_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_12ActionPerformed

    private void botton_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_13ActionPerformed

    private void botton_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_14ActionPerformed

    private void botton_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_15ActionPerformed

    private void botton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_6ActionPerformed

    private void botton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_7ActionPerformed

    private void botton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_8ActionPerformed

    private void botton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_9ActionPerformed

    private void botton_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_10ActionPerformed

    private void botton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_1ActionPerformed

    private void botton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_2ActionPerformed

    private void botton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_3ActionPerformed

    private void botton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_4ActionPerformed

    private void botton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_5ActionPerformed

    private void jComboBox_sexoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_sexoJugadorActionPerformed
        // TODO add your handling code here:
        if (jComboBox_sexoJugador.getSelectedItem().toString() == "Hombre") {
            jLabel_avatarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/RedHGSS.gif")));
        } else {
            jLabel_avatarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/CynthiaPlatinum.gif")));
        }
    }//GEN-LAST:event_jComboBox_sexoJugadorActionPerformed

    private void botton_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_crearUsuarioActionPerformed
        // TODO add your handling code here:
        Agregar_usuario.setSize(1280, 900);
        Agregar_usuario.setLocationRelativeTo(this);
        Agregar_usuario.setVisible(true);
    }//GEN-LAST:event_botton_crearUsuarioActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jTextField_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_edadActionPerformed
        // TODO add your handling code here:Kanto
    }//GEN-LAST:event_jTextField_edadActionPerformed

    private void jComboBox_regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_regionActionPerformed
        // TODO add your handling code here:
        if (jComboBox_region.getSelectedItem().toString() == "Kanto") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-HGSS_Kanto.png")));
        } else if (jComboBox_region.getSelectedItem().toString() == "Hoenn") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-Hoenn_ORAS.png")));
        } else if (jComboBox_region.getSelectedItem().toString() == "Sinnoh") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-Pt_Sinnoh.png")));
        } else if (jComboBox_region.getSelectedItem().toString() == "Unova") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-Unova_B2W2_alt.png")));
        } else if (jComboBox_region.getSelectedItem().toString() == "Kalos") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-Kalos_alt.png")));
        } else if (jComboBox_region.getSelectedItem().toString() == "Alola") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-Alola_artwork.png")));
        } else if (jComboBox_region.getSelectedItem().toString() == "Johto") {
            jLabel_regiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/300px-JohtoMap.png")));
        }
    }//GEN-LAST:event_jComboBox_regionActionPerformed

    private void jTextField_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_contraseñaActionPerformed

    private void botton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_SalirActionPerformed
        // TODO add your handling code here:
        pokedex.setSize(900, 700);
        pokedex.setLocationRelativeTo(this);
        pokedex.setVisible(true);
    }//GEN-LAST:event_botton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pokidex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pokidex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pokidex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pokidex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pokidex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar_Pokemon;
    private javax.swing.JDialog Agregar_usuario;
    private javax.swing.JDialog Login;
    private javax.swing.JButton botton_1;
    private javax.swing.JButton botton_10;
    private javax.swing.JButton botton_11;
    private javax.swing.JButton botton_12;
    private javax.swing.JButton botton_13;
    private javax.swing.JButton botton_14;
    private javax.swing.JButton botton_15;
    private javax.swing.JButton botton_16;
    private javax.swing.JButton botton_17;
    private javax.swing.JButton botton_18;
    private javax.swing.JButton botton_19;
    private javax.swing.JButton botton_2;
    private javax.swing.JButton botton_20;
    private javax.swing.JButton botton_21;
    private javax.swing.JButton botton_22;
    private javax.swing.JButton botton_23;
    private javax.swing.JButton botton_24;
    private javax.swing.JButton botton_25;
    private javax.swing.JButton botton_3;
    private javax.swing.JButton botton_4;
    private javax.swing.JButton botton_5;
    private javax.swing.JButton botton_6;
    private javax.swing.JButton botton_7;
    private javax.swing.JButton botton_8;
    private javax.swing.JButton botton_9;
    private javax.swing.JButton botton_Salir;
    private javax.swing.JButton botton_crearUsuario;
    private javax.swing.JButton botton_login;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JComboBox<String> jComboBox_region;
    private javax.swing.JComboBox<String> jComboBox_sexoJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_avatarJugador;
    private javax.swing.JLabel jLabel_edad;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_nombre1;
    private javax.swing.JLabel jLabel_region;
    private javax.swing.JLabel jLabel_regiones;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JTextField jTextField_contraseña;
    private javax.swing.JTextField jTextField_edad;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JDialog pokedex;
    // End of variables declaration//GEN-END:variables
}
